### ISSUE TITLE
Please update readme?

### ISSUE THREAD

**Issue by McGeaverBeaver** [mtongnz/unraidWOLcmd#1]
Hi there,

Not sure if I am just implementing this differently? but I found a few, of what I think are typos that have caused some extra troubleshooting.

1) typo
> Run this command from the docker's config directory (probably /mnt/users/appdata/wolReceive/).
> mkfifo /fifo

this should read:

> Run this command from the docker's config directory (probably /mnt/user/appdata/wolReceive/).
> mkfifo fifo

2) regarding script move, why is this required?  putting the script inside the appdata dir used for the config works and no file moves required.. am I missing an understanding of somethning, why were you doing it this way? 

putting vmControl.sh , inside of " /mnt/user/appdata/wolReceive/scripts "  permissions of  744 rwxr--r--

config.yaml:
`
" cmd: "echo \"/mnt/user/appdata/wolReceive/scripts/vmControl.sh 'MY-VM' start\" > /config/fifo" " 
`

Thanks for the script and work put in on this, it was very helpful!

**Comment by mtongnz** [comment]
1. Fixed the typo.
2. I Can't remember the reason behind script move other than that's where I store all my scripts and unRaid insists on deleting it on restart.  It's not essential (as you found) but I shared it if anyone wanted it.  I like the simplicity of using /scripts/ as many of my scripts are used by multiple services/user scripts.

As a side note, most use cases for this project are now natively supported in unRaid with built in WOL support.  I haven't tried it yet but it's there.

Thanks heaps for the feedback.

**Comment by McGeaverBeaver** [comment]
Awesome! 

Re #2 , You could look at maybe using   " /boot/config/plugins/user.scripts/scripts/ " 

> As a side note, most use cases for this project are now natively supported in unRaid with built in WOL support. I haven't tried it yet but it's there.

Yes, but I can't get that to work.. WOL packets are clearly making it to the parent interface, I can WOL the physical server.. but not any of the VMs and I have used the plugin.. as to my hunt to fix that, I found this.

**Comment by mtongnz** [comment]
I made this as I couldn't get the WOL plugin to work for VMs about a year ago (before native support). I decided to make it able to run any command so I could easily trigger everything in 1 place editor - scripts, start/stop VMs/containers, and any other crazy things I decide to do in the future.
I've got a selection of bizarre scripts to solve niche use cases on my server :)
